In [1]:
import sys
import numpy as np
sys.path.append('./src')

In [2]:
from GridWorld import GridWorld
from TD0 import TD0

env = GridWorld(size=5, obstacles=[(1,1),(2,2)], icy_floors=[(1,2)])

# 4. Temporal-Difference

## 4-1. Evaluation

In [3]:
target_policy = np.random.dirichlet(np.ones(len(env.actions)), size = len(env.states))

td0 = TD0(env)

Opt_V_TD0 = td0.evaluation(target_policy)

print(f"Optimal V using TD0:\n{Opt_V_TD0.reshape(5, 5)}")

Optimal V using TD0:
[[-36.48142286 -32.41818734 -29.39277472 -29.03624804 -30.48267512]
 [-34.63349313   0.         -29.71062573 -28.68018419 -25.35368182]
 [-23.42498695 -25.67418463   0.         -27.26163113 -22.61090051]
 [-21.93249835 -21.83567183 -19.49085309 -16.63362756  -5.56824212]
 [-21.67319625 -21.58367799 -15.43652777 -13.56640634   0.        ]]


## 4-2. SARSA

In [13]:
Opt_p_SARSA, Opt_Q_SARSA = td0.SARSA(alpha = 0.1, gamma = 0.99, max_steps=1000, max_iter=100000)

print("========= Optimal Policy - SARSA =========")
print(Opt_p_SARSA)
print("\n========= Optimal Q - SARSA =========")
print(Opt_Q_SARSA)

========= Optimal Policy - SARSA =========
[[2.500000e-06 9.999925e-01 2.500000e-06 2.500000e-06]
 [2.500000e-06 2.500000e-06 2.500000e-06 9.999925e-01]
 [2.500000e-06 2.500000e-06 2.500000e-06 9.999925e-01]
 [2.500000e-06 2.500000e-06 2.500000e-06 9.999925e-01]
 [2.500000e-06 9.999925e-01 2.500000e-06 2.500000e-06]
 [2.500000e-06 9.999925e-01 2.500000e-06 2.500000e-06]
 [9.999925e-01 2.500000e-06 2.500000e-06 2.500000e-06]
 [9.999925e-01 2.500000e-06 2.500000e-06 2.500000e-06]
 [2.500000e-06 2.500000e-06 2.500000e-06 9.999925e-01]
 [2.500000e-06 9.999925e-01 2.500000e-06 2.500000e-06]
 [2.500000e-06 9.999925e-01 2.500000e-06 2.500000e-06]
 [2.500000e-06 9.999925e-01 2.500000e-06 2.500000e-06]
 [9.999925e-01 2.500000e-06 2.500000e-06 2.500000e-06]
 [2.500000e-06 2.500000e-06 2.500000e-06 9.999925e-01]
 [2.500000e-06 9.999925e-01 2.500000e-06 2.500000e-06]
 [2.500000e-06 2.500000e-06 2.500000e-06 9.999925e-01]
 [2.500000e-06 2.500000e-06 2.500000e-06 9.999925e-01]
 [2.500000e-06 9.99992