## 1. GridWorld

In [1]:
import sys
import numpy as np
sys.path.append('./src')

from GridWorld import GridWorld

In [2]:
print("=== obstacles=None ===")
env = GridWorld(size=5)
env.reset()
env.render()

=== obstacles=None ===
A . . . .
. . . . .
. . . . .
. . . . .
. . . . G



In [3]:
print("=== Obstacles case ===")
env2 = GridWorld(size=5, obstacles=[(1,1), (2,2), (3,1)])
env2.reset()
env2.render()

=== Obstacles case ===
A . . . .
. X . . .
. . X . .
. X . . .
. . . . G



In [4]:
print("=== Obstacles at start case ===")
try:
    env3 = GridWorld(size=5, obstacles=[(0,0)])
except AssertionError as e:
    print(f"AssertionError: {e}")

try:
    env4 = GridWorld(size=5, obstacles=[(4,4)])
except AssertionError as e:
    print(f"AssertionError: {e}")

=== Obstacles at start case ===
AssertionError: Obstacles at the start or goal position.
AssertionError: Obstacles at the start or goal position.


In [5]:
print("=== Bondary test ===")
env6 = GridWorld(size=5)
env6.reset()
for _ in range(5): 
    state, reward, move, done = env6.step(2)  # left
    print(f"state: {state}, reward: {reward}")

=== Bondary test ===
state: (0, 0), reward: -1
state: (0, 0), reward: -1
state: (0, 0), reward: -1
state: (0, 0), reward: -1
state: (0, 0), reward: -1


In [6]:
print("=== Step test ===")
env5 = GridWorld(size=5, obstacles=[(1,1)])
env5.reset()
for action in [1, 3, 3, 1, 3]: 
    state, reward, move, done = env5.step(action)
    print(f"state: {state}, reward: {reward}, move: {move}, done: {done}")
env5.render()

=== Step test ===
state: (1, 0), reward: -0.1, move: Down, done: False
state: (1, 0), reward: -1, move: None, done: False
state: (1, 0), reward: -1, move: None, done: False
state: (2, 0), reward: -0.1, move: Down, done: False
state: (2, 1), reward: -0.1, move: Right, done: False
. . . . .
. X . . .
. A . . .
. . . . .
. . . . G



In [7]:
print("=== Icy floor test ===")
env6 = GridWorld(size=5, obstacles=[(1,1), (2,3)], icy_floors=[(0,1), (3,2), (3,3), (1,3)])
env6.reset()

action_list = ['Up', 'Down', 'Left', 'Right']
for action in [1, 2, 3, 1, 3, 0, 1, 3, 3, 2, 3, 2, 3, 0]: 
    state, reward, move, done = env6.step(action)
    print(f"state: {state}, reward: {reward}, action: {action_list[action]}, move: {move}, done: {done}")
env6.render()

=== Icy floor test ===
state: (1, 0), reward: -0.1, action: Down, move: Down, done: False
state: (1, 0), reward: -1, action: Left, move: None, done: False
state: (1, 0), reward: -1, action: Right, move: None, done: False
state: (2, 0), reward: -0.1, action: Down, move: Down, done: False
state: (2, 1), reward: -0.1, action: Right, move: Right, done: False
state: (2, 1), reward: -1, action: Up, move: None, done: False
state: (3, 1), reward: -0.1, action: Down, move: Down, done: False
state: (3, 2), reward: -0.1, action: Right, move: Right, done: False
state: (3, 3), reward: -0.1, action: Right, move: Right, done: False
state: (4, 3), reward: -0.1, action: Left, move: Down, done: False
state: (4, 4), reward: 1, action: Right, move: Right, done: True
state: (4, 3), reward: -0.1, action: Left, move: Left, done: False
state: (4, 4), reward: 1, action: Right, move: Right, done: True
state: (3, 4), reward: -0.1, action: Up, move: Up, done: False
. O . . .
. X . O .
. . . X .
. . O O A
. . . . 

# 2. Dynamic Programming
## 2-1. Policy Evaluation

In [9]:
from DP_policyeval import DP_policyeval

env = GridWorld(size=5, obstacles=[(1,1),(2,2)], icy_floors=[(1,2)])
states = [(r,c) for r in range(5) for c in range(5)]
actions = [0, 1, 2, 3]

dp = DP_policyeval(env, states, actions)
V = dp.eval()
print(V.reshape(5, 5))
print(f"\n   Highest Value State: {dp.index_to_state(np.argmax(V))}, {max(V):.4f}")

[[-37.41814417 -37.06295715 -35.98304509 -35.30767557 -35.37701773]
 [-37.06295715 -36.12718443 -35.7192356  -34.6764093  -34.65351608]
 [-35.98304509 -35.7192356  -34.62202972 -34.02224056 -33.99413593]
 [-35.30767557 -34.6764093  -34.02224056 -33.45768509 -33.36702424]
 [-35.37701773 -34.65351608 -33.99413593 -33.36702424 -33.79539805]]

   Highest Value State: (3, 4), -33.3670
